version: '3'
services:
  reverse-proxy:
    container_name: reverse-proxy
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/homepage-exceptions.conf:/etc/nginx/homepage-exceptions.conf:ro
      - ./nginx/ssl-options.conf:/etc/nginx/ssl-options.conf:ro
      - ./nginx/dhparam:/etc/nginx/dhparam:ro
      - /etc/letsencrypt/live/29th.org/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/29th.org/privkey.pem:/etc/nginx/certs/privkey.pem:ro
      - /etc/letsencrypt/live/29th.org/chain.pem:/etc/nginx/certs/chain.pem:ro

  app:
    container_name: app
    image: 29th/personnel-app:latest
    restart: always
    environment:
      BASE_URL: https://personnel.29th.org
      API_HOST: https://api.29th.org
      COAT_DIR: https://api.29th.org/coats
      FORUM_VANILLA_BASE_URL: https://forums.29th.org
      FORUM_SMF_BASE_URL: https://29th.org/forums
      FORUM_DISCOURSE_BASE_URL: https://discourse.29th.org
      WIKI_URL: https://29th.org/wiki

  api:
    container_name: api
    image: 29th/personnel-api:latest
    restart: always
    volumes:
      - /mnt/user_images/coats:/var/www/html/coats
    environment:
      DB_DEFAULT_DATABASE: $PERSONNEL_DB_DATABASE
      DB_DEFAULT_HOSTNAME: $PERSONNEL_DB_HOSTNAME
      DB_DEFAULT_USERNAME: $PERSONNEL_DB_USERNAME
      DB_DEFAULT_PASSWORD: $PERSONNEL_DB_PASSWORD
      DB_DEFAULT_PORT: $PERSONNEL_DB_PORT
      DB_FORUMS_DATABASE: $FORUMS_DB_DATABASE
      DB_FORUMS_HOSTNAME: $FORUMS_DB_HOSTNAME
      DB_FORUMS_USERNAME: $FORUMS_DB_USERNAME
      DB_FORUMS_PASSWORD: $FORUMS_DB_PASSWORD
      DB_FORUMS_PORT: $FORUMS_DB_PORT
      ENCRYPTION_KEY: $PERSONNEL_ENCRYPTION_KEY
      ADMIN_API_KEY: $PERSONNEL_ADMIN_API_KEY
      BASE_URL: https://api.29th.org
      CORS_HOST: https://personnel.29th.org
      VANILLA_BASE_URL: https://forums.29th.org
      VANILLA_API_KEY: $VANILLA_API_KEY
      VANILLA_COOKIE_NAME: Vanilla
      VANILLA_SECRET_KEY: $FORUMS_COOKIE_SALT
      DISCOURSE_BASE_URL: https://discourse.29th.org
      DISCOURSE_API_KEY: $DISCOURSE_API_KEY
      DISCOURSE_COOKIE_NAME: discourse_jwt
      DISCOURSE_SECRET_KEY: $DISCOURSE_SECRET_KEY
      ENVIRONMENT: production
      DIR_COAT_PUBLIC: /var/www/html/coats/

  forums:
    container_name: forums
    image: 29th/forums:latest
    restart: always
    volumes:
      - /mnt/user_images/uploads:/var/www/html/uploads
    environment:
      DB_HOSTNAME: $FORUMS_DB_HOSTNAME:$FORUMS_DB_PORT
      DB_DATABASE: $FORUMS_DB_DATABASE
      DB_USERNAME: $FORUMS_DB_USERNAME
      DB_PASSWORD: $FORUMS_DB_PASSWORD
      COOKIE_SALT: $FORUMS_COOKIE_SALT
      COOKIE_DOMAIN: 29th.org
      UPDATE_TOKEN: $FORUMS_UPDATE_TOKEN
      MAIL_FROM_NAME: 29th ID
      MAIL_FROM_ADDRESS: noreply@29th.org
      MAIL_SMTP_HOSTNAME: $FORUMS_MAIL_SMTP_HOSTNAME
      MAIL_SMTP_USERNAME: $FORUMS_MAIL_SMTP_USERNAME
      MAIL_SMTP_PASSWORD: $FORUMS_MAIL_SMTP_PASSWORD
      MAIL_SMTP_PORT: $FORUMS_MAIL_SMTP_PORT
      MAIL_SMTP_SECURITY: $FORUMS_MAIL_SMTP_SECURITY
      CAPTCHA_PRIVATE_KEY: $FORUMS_CAPTCHA_PRIVATE_KEY
      CAPTCHA_PUBLIC_KEY: $FORUMS_CAPTCHA_PUBLIC_KEY
      PERSONNEL_HOST_NAME: personnel.29th.org
      DEBUG: 0

  v3:
    container_name: v3
    image: 29th/personnel-v3:latest
    restart: always
    tmpfs: /usr/src/app/tmp
    user: root
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 'true'
      RAILS_LOG_TO_STDOUT: 'true'
      DATABASE_URL: $PERSONNEL_DB_URL
      SECRET_KEY_BASE: $SECRET_KEY_BASE
      VANILLA_BASE_URL: https://forums.29th.org
      VANILLA_API_KEY: $VANILLA_API_KEY
      DISCOURSE_BASE_URL: https://discourse.29th.org
      DISCOURSE_API_KEY: $DISCOURSE_API_KEY
      V2_ADMIN_API_KEY: $PERSONNEL_ADMIN_API_KEY
      V2_API_BASE_URL: https://api.29th.org
      FORUMS_COOKIE_NAME: Vanilla
      FORUMS_SECRET_KEY: $FORUMS_COOKIE_SALT
      STORAGE_ENDPOINT: https://nyc3.digitaloceanspaces.com
      STORAGE_BUCKET: 29th-uploads
      STORAGE_REGION: nyc3
      STORAGE_ACCESS_KEY_ID: $STORAGE_ACCESS_KEY_ID
      STORAGE_SECRET_ACCESS_KEY: $STORAGE_SECRET_ACCESS_KEY
      STORAGE_PUBLIC_HOST: https://uploads.29th.org

  bitwarden:
    container_name: bitwarden
    image: bitwardenrs/server-mysql
    restart: always
    volumes:
      - /mnt/user_images/bitwarden-data/:/data/
    environment:
      DATABASE_URL: mysql://$BITWARDEN_DB_USERNAME:$BITWARDEN_DB_PASSWORD@$BITWARDEN_DB_HOSTNAME:$BITWARDEN_DB_PORT/$BITWARDEN_DB_DATABASE
      ADMIN_TOKEN: $BITWARDEN_ADMIN_TOKEN
      ENABLE_DB_WAL: 'false'
      RUST_BACKTRACE: 1 # detailed crash logs
      SIGNUPS_ALLOWED: 'false'
      SHOW_PASSWORD_HINT: 'false'
      DOMAIN: https://bitwarden.29th.org
      SMTP_HOST: $FORUMS_MAIL_SMTP_HOSTNAME
      SMTP_USERNAME: $FORUMS_MAIL_SMTP_USERNAME
      SMTP_PASSWORD: $FORUMS_MAIL_SMTP_PASSWORD
      SMTP_PORT: $FORUMS_MAIL_SMTP_PORT
      SMTP_SSL: 'true'
      SMTP_FROM: noreply@29th.org
      SMTP_EXPLICIT_TLS: 'true'
