version: '3'
services:
  reverse-proxy:
    image: caddy/caddy:v2.0.0-beta.17
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    user: root
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/etc/caddy/certs

  homepage:
    image: nginx:1.17.7
    container_name: homepage
    volumes:
      - ./homepage.conf:/etc/nginx/nginx.conf

  app:
    build: ./personnel-app
    container_name: app
    command: npm run dev
    volumes:
      - ./personnel-app/src:/home/node/app/src
    environment:
      BASE_URL: https://personnel.29th.local
      API_HOST: https://api.29th.local
      COAT_DIR: https://api.29th.local/coats
      FORUM_VANILLA_BASE_URL: https://forums.29th.local
      FORUM_SMF_BASE_URL: https://29th.org/forums
      WIKI_URL: https://29th.org/wiki

  api:
    build: ./personnel-api
    container_name: api
    volumes:
      - ./personnel-api/application:/var/www/html/application
      - ./coats:/var/www/html/coats
    environment:
      DB_DEFAULT_DATABASE: personnel_v2
      DB_DEFAULT_HOSTNAME: db-personnel
      DB_DEFAULT_USERNAME: root
      DB_DEFAULT_PASSWORD: pwd
      DB_DEFAULT_PORT: 3306
      DB_FORUMS_DATABASE: vanilla
      DB_FORUMS_HOSTNAME: db-forums
      DB_FORUMS_USERNAME: root
      DB_FORUMS_PASSWORD: pwd
      DB_FORUMS_PORT: 3306
      ENCRYPTION_KEY: dev
      BASE_URL: https://api.29th.local
      CORS_HOST: https://personnel.29th.local
      VANILLA_BASE_URL: http://forums
      VANILLA_ACCESS_TOKEN: $FORUMS_PERSONAL_ACCESS_TOKEN
      VANILLA_COOKIE_NAME: Vanilla
      VANILLA_COOKIE_DOMAIN: 29th.local
      VANILLA_COOKIE_PATH: /
      VANILLA_COOKIE_HASH_METHOD: md5
      VANILLA_COOKIE_SALT: dev
      ENVIRONMENT: production
      DIR_COAT_PUBLIC: /var/www/html/coats/

  forums:
    build: ./forums
    container_name: forums
    volumes:
      - ./uploads:/var/www/html/uploads
    environment:
      DB_HOSTNAME: db-forums
      DB_DATABASE: vanilla
      DB_USERNAME: root
      DB_PASSWORD: pwd
      COOKIE_SALT: dev
      COOKIE_DOMAIN: 29th.local
      UPDATE_TOKEN: dev
      PERSONNEL_HOST_NAME: personnel.29th.local
      DEBUG: 1

  db-personnel:
    image: mysql:8
    container_name: db-personnel
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--sql-mode=ALLOW_INVALID_DATES',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db/personnel.sql:/docker-entrypoint-initdb.d/personnel.sql
      - db-personnel-persistence:/var/lib/mysql
    environment:
      MYSQL_DATABASE: personnel_v2
      MYSQL_ROOT_PASSWORD: pwd

  db-forums:
    image: mysql:8
    container_name: db-forums
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--sql-mode=ALLOW_INVALID_DATES',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./db/vanilla.sql:/docker-entrypoint-initdb.d/vanilla.sql
      - db-vanilla-persistence:/var/lib/mysql
    environment:
      MYSQL_DATABASE: vanilla
      MYSQL_ROOT_PASSWORD: pwd

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOSTS: db-forums,db-personnel
      PMA_USER: root
      PMA_PASSWORD: pwd

volumes:
  db-personnel-persistence:
  db-vanilla-persistence:
