version: '3'
services:
  reverse-proxy:
    container_name: reverse-proxy
    image: caddy/caddy:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    user: root
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-config:/root/.config/caddy
      - caddy-data:/root/.local/share/caddy

  homepage:
    container_name: homepage
    image: nginx:1.17.7
    restart: always
    volumes:
      - ./homepage.conf:/etc/nginx/nginx.conf

  app:
    container_name: app
    image: 29th/personnel-app:latest
    restart: always
    environment:
      BASE_URL: https://personnel.29th.xyz
      API_HOST: https://api.29th.xyz
      COAT_DIR: https://api.29th.xyz/coats
      FORUM_VANILLA_BASE_URL: https://forums.29th.xyz
      FORUM_SMF_BASE_URL: https://29th.org/forums
      WIKI_URL: https://29th.xyz/wiki

  # TODO: Add coats volume
  api:
    container_name: api
    image: 29th/personnel-api:latest
    restart: always
    environment:
      DB_DEFAULT_DATABASE: $PERSONNEL_DB_DATABASE
      DB_DEFAULT_HOSTNAME: $PERSONNEL_DB_HOSTNAME
      DB_DEFAULT_USERNAME: $PERSONNEL_DB_USERNAME
      DB_DEFAULT_PASSWORD: $PERSONNEL_DB_PASSWORD
      DB_DEFAULT_PORT: $PERSONNEL_DB_PORT
      DB_FORUMS_DATABASE: $FORUMS_DB_DATABASE
      DB_FORUMS_HOSTNAME: $FORUMS_DB_HOSTNAME
      DB_FORUMS_USERNAME: $FORUMS_DB_USERNAME
      DB_FORUMS_PASSWORD: $FORUMS_DB_PASSWORD
      DB_FORUMS_PORT: $FORUMS_DB_PORT
      ENCRYPTION_KEY: $PERSONNEL_ENCRYPTION_KEY
      CORS_HOST: https://personnel.29th.xyz
      VANILLA_COOKIE_NAME: Vanilla
      VANILLA_COOKIE_DOMAIN: 29th.xyz
      VANILLA_COOKIE_PATH: /
      VANILLA_COOKIE_HASH_METHOD: md5
      VANILLA_COOKIE_SALT: $FORUMS_COOKIE_SALT
      ENVIRONMENT: production
      # DIR_COAT_RESOURCES: 
      # DIR_COAT_PUBLIC: 

  forums:
    container_name: forums
    image: 29th/forums:latest
    restart: always
    volumes:
      - ./uploads:/var/www/html/uploads
    environment:
      DB_HOSTNAME: $FORUMS_DB_HOSTNAME:$FORUMS_DB_PORT
      DB_DATABASE: $FORUMS_DB_DATABASE
      DB_USERNAME: $FORUMS_DB_USERNAME
      DB_PASSWORD: $FORUMS_DB_PASSWORD
      COOKIE_SALT: $FORUMS_COOKIE_SALT
      COOKIE_DOMAIN: 29th.xyz
      UPDATE_TOKEN: $FORUMS_UPDATE_TOKEN
      MAIL_FROM_NAME: 29th ID
      MAIL_FROM_ADDRESS: noreply@29th.org
      MAIL_SMTP_HOSTNAME: $FORUMS_MAIL_SMTP_HOSTNAME
      MAIL_SMTP_USERNAME: $FORUMS_MAIL_SMTP_USERNAME
      MAIL_SMTP_PASSWORD: $FORUMS_MAIL_SMTP_PASSWORD
      MAIL_SMTP_PORT: $FORUMS_MAIL_SMTP_PORT
      MAIL_SMTP_SECURITY: $FORUMS_MAIL_SMTP_SECURITY
      CAPTCHA_PRIVATE_KEY: $FORUMS_CAPTCHA_PRIVATE_KEY
      CAPTCHA_PUBLIC_KEY: $FORUMS_CAPTCHA_PUBLIC_KEY
      DEBUG: 0

volumes:
  caddy-config:
  caddy-data:
