version: '3'
services:
  reverse-proxy:
    image: nginx:1.17.7
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  app:
    build: ./personnel-app
    container_name: app
    command: npm run dev
    volumes:
      - ./personnel-app/src:/home/node/app/src
    environment:
      BASE_URL: http://personnel.29th.local
      API_HOST: http://api.29th.local
      COAT_DIR: http://api.29th.local/coats
      FORUM_VANILLA_BASE_URL: http://forums.29th.local
      FORUM_SMF_BASE_URL: http://29th.org/forums
      WIKI_URL: https://29th.org/wiki

  api:
    build: ./personnel-api
    container_name: api
    volumes:
      - ./personnel-api/application:/var/www/html/application
    environment:
      DB_DEFAULT_DATABASE: personnel_v2
      DB_DEFAULT_HOSTNAME: db-personnel
      DB_DEFAULT_USERNAME: root
      DB_DEFAULT_PASSWORD: pwd
      DB_DEFAULT_PORT: 3306
      DB_FORUMS_DATABASE: vanilla
      DB_FORUMS_HOSTNAME: db-vanilla
      DB_FORUMS_USERNAME: root
      DB_FORUMS_PASSWORD: pwd
      DB_FORUMS_PORT: 3307
      ENCRYPTION_KEY: dev
      CORS_HOST: http://personnel.29th.local
      VANILLA_COOKIE_NAME: Vanilla
      VANILLA_COOKIE_DOMAIN: .29th.local
      VANILLA_COOKIE_PATH: /
      VANILLA_COOKIE_HASH_METHOD: md5
      VANILLA_COOKIE_SALT: dev
      ENVIRONMENT: development
      # DIR_COAT_RESOURCES: 
      # DIR_COAT_PUBLIC: 

  forums:
    build: ./forums
    container_name: forums
    volumes:
      - ./forums/uploads:/var/www/html/uploads
    environment:
      DB_HOSTNAME: db-vanilla
      DB_DATABASE: vanilla
      DB_USERNAME: root
      DB_PASSWORD: pwd
      COOKIE_SALT: dev
      UPDATE_TOKEN: dev
      DEBUG: 1

  db-personnel:
    image: mysql:8
    container_name: db-personnel
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--sql-mode=ALLOW_INVALID_DATES',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db/personnel.sql:/docker-entrypoint-initdb.d/personnel.sql
      - db-personnel-persistence:/var/lib/mysql
    environment:
      MYSQL_DATABASE: personnel_v2
      MYSQL_ROOT_PASSWORD: pwd

  db-vanilla:
    image: mysql:8
    container_name: db-forums
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--sql-mode=ALLOW_INVALID_DATES',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./db/vanilla.sql:/docker-entrypoint-initdb.d/vanilla.sql
      - db-vanilla-persistence:/var/lib/mysql
    environment:
      MYSQL_DATABASE: vanilla
      MYSQL_ROOT_PASSWORD: pwd

volumes:
  db-personnel-persistence:
  db-vanilla-persistence:
