version: '3'
services:
  reverse-proxy:
    container_name: reverse-proxy
    image: caddy/caddy:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    user: root
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile
      - caddy-config:/root/.config/caddy
      - caddy-data:/root/.local/share/caddy

  homepage:
    container_name: homepage
    image: nginx:1.17.7
    restart: always
    volumes:
      - ./homepage.conf:/etc/nginx/nginx.conf

  app:
    container_name: app
    image: 29th/personnel-app:latest
    restart: always
    environment:
      BASE_URL: https://personnel.29th.org
      API_HOST: https://api.29th.org
      COAT_DIR: https://api.29th.org/coats
      FORUM_VANILLA_BASE_URL: https://forums.29th.org
      FORUM_SMF_BASE_URL: https://29th.org/forums
      WIKI_URL: https://29th.org/wiki

  api:
    container_name: api
    image: 29th/personnel-api:latest
    restart: always
    volumes:
      - /mnt/user_images/coats:/var/www/html/coats
    environment:
      DB_DEFAULT_DATABASE: $PERSONNEL_DB_DATABASE
      DB_DEFAULT_HOSTNAME: $PERSONNEL_DB_HOSTNAME
      DB_DEFAULT_USERNAME: $PERSONNEL_DB_USERNAME
      DB_DEFAULT_PASSWORD: $PERSONNEL_DB_PASSWORD
      DB_DEFAULT_PORT: $PERSONNEL_DB_PORT
      DB_FORUMS_DATABASE: $FORUMS_DB_DATABASE
      DB_FORUMS_HOSTNAME: $FORUMS_DB_HOSTNAME
      DB_FORUMS_USERNAME: $FORUMS_DB_USERNAME
      DB_FORUMS_PASSWORD: $FORUMS_DB_PASSWORD
      DB_FORUMS_PORT: $FORUMS_DB_PORT
      ENCRYPTION_KEY: $PERSONNEL_ENCRYPTION_KEY
      BASE_URL: https://api.29th.org
      CORS_HOST: https://personnel.29th.org
      VANILLA_BASE_URL: https://forums.29th.org
      VANILLA_ACCESS_TOKEN: $FORUMS_PERSONAL_ACCESS_TOKEN
      VANILLA_COOKIE_NAME: Vanilla
      VANILLA_COOKIE_DOMAIN: 29th.org
      VANILLA_COOKIE_PATH: /
      VANILLA_COOKIE_HASH_METHOD: md5
      VANILLA_COOKIE_SALT: $FORUMS_COOKIE_SALT
      ENVIRONMENT: production
      DIR_COAT_PUBLIC: /var/www/html/coats/

  forums:
    container_name: forums
    image: 29th/forums:latest
    restart: always
    volumes:
      - /mnt/user_images/uploads:/var/www/html/uploads
    environment:
      DB_HOSTNAME: $FORUMS_DB_HOSTNAME:$FORUMS_DB_PORT
      DB_DATABASE: $FORUMS_DB_DATABASE
      DB_USERNAME: $FORUMS_DB_USERNAME
      DB_PASSWORD: $FORUMS_DB_PASSWORD
      COOKIE_SALT: $FORUMS_COOKIE_SALT
      COOKIE_DOMAIN: 29th.org
      UPDATE_TOKEN: $FORUMS_UPDATE_TOKEN
      MAIL_FROM_NAME: 29th ID
      MAIL_FROM_ADDRESS: noreply@29th.org
      MAIL_SMTP_HOSTNAME: $FORUMS_MAIL_SMTP_HOSTNAME
      MAIL_SMTP_USERNAME: $FORUMS_MAIL_SMTP_USERNAME
      MAIL_SMTP_PASSWORD: $FORUMS_MAIL_SMTP_PASSWORD
      MAIL_SMTP_PORT: $FORUMS_MAIL_SMTP_PORT
      MAIL_SMTP_SECURITY: $FORUMS_MAIL_SMTP_SECURITY
      CAPTCHA_PRIVATE_KEY: $FORUMS_CAPTCHA_PRIVATE_KEY
      CAPTCHA_PUBLIC_KEY: $FORUMS_CAPTCHA_PUBLIC_KEY
      PERSONNEL_HOST_NAME: personnel.29th.org
      DEBUG: 0

  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: always
    command: --admin-password=$PORTAINER_ADMIN_PASSWORD
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

  bitwarden:
    container_name: bitwarden
    image: bitwardenrs/server-mysql
    restart: always
    volumes:
      - /mnt/user_images/bitwarden-data/:/data/
    environment:
      DATABASE_URL: mysql://$BITWARDEN_DB_USERNAME:$BITWARDEN_DB_PASSWORD@$BITWARDEN_DB_HOSTNAME:$BITWARDEN_DB_PORT/$BITWARDEN_DB_DATABASE
      ADMIN_TOKEN: $BITWARDEN_ADMIN_TOKEN
      ENABLE_DB_WAL: 'false'
      RUST_BACKTRACE: 1 # detailed crash logs
      SIGNUPS_ALLOWED: 'false'
      SHOW_PASSWORD_HINT: 'false'
      DOMAIN: https://bitwarden.29th.org
      SMTP_HOST: $FORUMS_MAIL_SMTP_HOSTNAME
      SMTP_USERNAME: $FORUMS_MAIL_SMTP_USERNAME
      SMTP_PASSWORD: $FORUMS_MAIL_SMTP_PASSWORD
      SMTP_PORT: $FORUMS_MAIL_SMTP_PORT
      SMTP_SSL: 'true'
      SMTP_FROM: noreply@29th.org
      SMTP_EXPLICIT_TLS: 'true'


  # Discourse services, for temporary use
  discourse-app:
    image: bitnami:discourse:2
    network: discourse
    depends_on:
      - discourse-db
      - discourse-redis
    volumes:
      - discourse-app-data:/bitnami
    environment:
      POSTGRESQL_HOST: discourse-db
      DISCOURSE_POSTGRESQL_NAME: $DISCOURSE_DB_DATABASE
      DISCOURSE_POSTGRESQL_USERNAME: $DISCOURSE_DB_USERNAME
      DISCOURSE_POSTGRESQL_PASSWORD: $DISCOURSE_DB_PASSWORD
      DISCOURSE_HOSTNAME: discourse.29th.org
      DISCOURSE_SITENAME: 29th Infantry Division
      REDIS_HOST: discourse-redis
      REDIS_PASSWORD: $DISCOURSE_REDIS_PASSWORD
      SMTP_HOST: $FORUMS_MAIL_SMTP_HOSTNAME
      SMTP_USER: $FORUMS_MAIL_SMTP_USERNAME
      SMTP_PASSWORD: $FORUMS_MAIL_SMTP_PASSWORD
      SMTP_PORT: $FORUMS_MAIL_SMTP_PORT

  discourse-db:
    image: bitnami/postgresql:11
    network: discourse
    volumes:
      - db-discourse-data:/bitnami/postgresql
    environment:
      POSTGRESQL_DATABASE: $DISCOURSE_DB_DATABASE
      POSTGRESQL_USERNAME: $DISCOURSE_DB_USERNAME
      POSTGRESQL_PASSWORD: $DISCOURSE_DB_PASSWORD

  discourse-redis:
    image: bitnami/redis:5.0
    network: discourse
    volumes:
      - redis-discourse-data:/bitnami
    environment:
      REDIS_PASSWORD: $DISCOURSE_REDIS_PASSWORD

  discourse-sidekiq:
    image: bitnami/discourse:2
    depends_on:
      - discourse-app
    volumes:
      discourse-sidekiq-data:/bitnami
    command: nami start --foreground discourse-sidekiq
    environment:
      DISCOURSE_POSTGRESQL_NAME: $DISCOURSE_DB_DATABASE
      DISCOURSE_POSTGRESQL_USERNAME: $DISCOURSE_DB_USERNAME
      DISCOURSE_POSTGRESQL_PASSWORD: $DISCOURSE_DB_PASSWORD
      DISCOURSE_HOST: discourse-app
      DISCOURSE_PORT: 3000
      DISCOURSE_HOSTNAME: discourse.29th.org

volumes:
  caddy-config:
  caddy-data:
  portainer-data:
  discourse-app-data:
  discourse-db-data:
  discourse-redis-data:
  discourse-sidekiq-data:
